### PR TITLE
Support alternative checkboxes

### PR DESCRIPTION
**Pull request by tobiasvl**
Many Obsidian themes support "alternative" checkboxes ([Minimal, for example](https://forum.obsidian.md/t/alternative-checkboxes-icon-bullets-copy-and-paste/35962/2)), where different characters inside the checkbox brackets give additional meaning to the checkbox.

Currently, this plugin will consider such alternative checkboxes (including the common `- [/]` checkbox, which means "incomplete") as finished, and not roll them over.

This PR changes this, so only `- [x]`/`- [X]` ("done") and `- [-]` ("canceled") are considered "finished" checkboxes. All other checkboxes are considered "unfinished" and will be rolled over.

### CODE REVIEW

**Comment by lumoe** [comment]
Thank you for your contribution @tobiasvl, looks like a neat feature which we should add. 

I just merged a bigger change into the codebase, which changes the way we extract ToDos from the documents and added some test.

Can I ask you to check out the newest version, add your changes and extend the test cases that cover the expected behaviour?

**Comment by tobiasvl** [comment]
@lumoe Okay, I think this should do it. I added a couple of tests I thought made sense (and fixed an unrelated typo in a separate commit). Let me know if you need anything else. (I haven't run the tests locally, and you need to approve running the CI, so we'll see if it works!)

**Comment by tobiasvl** [comment]
@lumoe Let me know if you need anything else from me!

**Comment by tim-hilt** [comment]
I think this is hard to standardize. `- [ ]` and `- [x] / - [X]` seem to be accepted by a big audience. Looking at the [minimal checklist-items](https://minimal.guide/Block+types/Checklists), I see multiple ones that could be referred to as "terminal status".

Shouldn't we add more characters to the regex if we are referring to the minimal-theme? Does it make sense for a very wide audience to refer to minimal-theme? Which other themes exist that enlarge the todo-items-functionality?

**Comment by tim-hilt** [comment]
> Those are part of the Markdown standard

Do you mean the GitHub-flavor?

> Which other ones do you see that could be referred to as "terminal"?

At least `- [>]` forwarded seems to signify that there is nothing else to do for this entry.

**Comment by tobiasvl** [comment]
> Do you mean the GitHub-flavor?

Yes, that's what I mean, sorry. It's not part of the official Markdown spec, I forgot since there are so many different ones. But, of course, it's also part of the Markdown supported by vanilla Obsidian (ie. with the standard theme).

By the way, GitLab's Markdown flavor supports an "inapplicable" checbox (`- [~]`), similar to (and originally suggested to be identical to) the "cancelled" `- [-]` one: https://docs.gitlab.com/ee/user/markdown.html#task-lists

> At least `- [>]` forwarded seems to signify that there is nothing else to do for this entry.

I can see that. I interpreted it as "forwarded to next sprint/day/whatever". I guess I fell victim to the same semantic interpretation problem!

**Comment by tim-hilt** [comment]
> it's also part of the Markdown supported by vanilla Obsidian

Of course - you're right. My first comment was pointless 🙈

**Comment by tim-hilt** [comment]
fixes https://github.com/lumoe/obsidian-rollover-daily-todos/issues/87

**Comment by hilsonp** [comment]
Hello,

Thank you for the plugin and for the cr.

As shown in this [comment](https://github.com/lumoe/obsidian-rollover-daily-todos/issues/87#issuecomment-1430548994), I adapted the regex to match my needs, 

Some people may like to only roll-over [ ] items.
Other may want to roll-over [ ] and [/].
Some other may want to roll over [ ], [/] and [>].
Yet other way roll over [?] as well but won't like the [>] to be rolled-over.

I think this is up to every one understanding/use of the different themes, semantic and markdown flavor.
Future will surely bring new things anyway.

Therefore, why not exposing a input box allowing people to enter a list of chars they would like to "roll-over" ?
The javascript would transform this string into the inner part of a regex bracket expression (escaping characters when needed (eg: \/ instead of /, \] instead of ])).
Having a space in this input box may not be easily visible so we may choose to always rollover [ ] and letting people put in the input box characters other than space that they would like to roll-over.

This would make the implementation very flexible and future proof.

**Comment by Rob-Conan** [comment]
Is there any update on this PR, I'd love to for this functionality to be added to Rollover Daily ToDos.

**Comment by chrabia** [comment]
hello. Are there any updates? Any reasons not to merge this MR?

**Review by chrabia — APPROVED** [review]

**Review by lumoe — APPROVED** [review]

**Comment by lumoe** [comment]
New plugin version with updated checkbox logic is live. Update available in Obsidian.

**Comment by dictionarymouse** [comment]
How does this work? Is the user able to define which task states rollover and which don't?

**Pull request merged**
