### PR TITLE
Add GiHub-Actions-Workflow to build via pnpm and Rollup

### PR DESCRIPTION
**Pull request by tim-hilt**
Let me know what you think :)

### CODE REVIEW

**Comment by lumoe** [comment]
I have never worked with pnpm before. It looks very interesting, and the GH Actions workflow especially! 
Going to test this out over the next, days. 
Thank you for this PR as well :)

**Comment by tim-hilt** [comment]
Cool, no worries! I have it set up on my fork. Go take a look around if you're interested to see what it adds!

**Review by lumoe — APPROVED** [review]

**Comment by lumoe** [comment]
As far as I understand it, pnpm can work as a drop-in replacement for npm right? In that case, we can leave it to the developer whether they want to use it or not. 

Thank you! I merged it to `gh_workflow_pnpm` branch in order to test GH workflow.

**Comment by tim-hilt** [comment]
pnpm is faster and has more readable output. If you don’t want to persist the pnpm-lock.yaml, the GitHub-action might not work. But that can be fixed by adding a command-line-flag.

Lockfiles are available to make building the application reproducible. Do you know why these never get persisted to git for Obsidian-Plugins?

**Comment by lumoe** [comment]
I persisted the `pnpm-lock.yaml` and `package-lock.json`. 

The problem I see is that these two lock files might be out-of-sync w.r.t. to the hashes of the versions? Is there best practice to keep them in sync?

**Comment by tim-hilt** [comment]
Hm.. best practice would be to choose/allow only one package-manager for a certain project. If you want to encourage multiple package-managers being used, you can still remove the lockfiles and run pnpm in the GitHub-Actions with the `--no-lockfile`-flag.

In this case you can still be sure future developers install the correct version by pinning the versions to patch-level by removing carets (^) in the package.json-file.

**Pull request merged**
